ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'anaconda/3-5.3.1'
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'python'
>> cuda-10.1_cudnn-7.6.5 has been loaded.
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 1-6,8: Exited with exit code 1
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 0,7,9-11: Exited with exit code 1
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 0-1,5-6,8: Exited with exit code 1
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-04: tasks 2-4,7,9-11: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
srun: error: saliksik-gpu-04: tasks 1-4,8-9,11: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ImportError: No module named src.experimenter_uncommented
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
srun: error: saliksik-gpu-04: tasks 0,5-7,10: Exited with exit code 1
