ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'anaconda/3-5.3.1'
>> python-3.8.2 has been loaded.
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'cuda/10.1_cudnn-7.6.5'
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-03: tasks 0-11: Exited with exit code 1
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
/usr/bin/python: No module named pip
srun: error: saliksik-gpu-03: tasks 0-11: Exited with exit code 1
Traceback (most recent call last):
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
ImportError: No module named src.experimenter_uncommented
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
Traceback (most recent call last):
  File "main.py", line 1, in <module>
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
ImportError: No module named src.experimenter_uncommented
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.experimenter_uncommented import gaframework, gaframework_gpu
ImportError: No module named src.experimenter_uncommented
srun: error: saliksik-gpu-03: tasks 0-11: Exited with exit code 1
