>> anaconda-3-5.3.1 has been loaded.
>> python-3.8.2 has been loaded.
>> cuda-10.1_cudnn-7.6.5 has been loaded.
WARNING: Skipping page https://pypi.org/simple/pip/ because the GET request got Content-Type: .The only supported Content-Type is text/html
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 39, in continue_create_empty_yaml
    ga_params = conf_load(savefile_name)
  File "main.py", line 15, in conf_load
    return ga_params
UnboundLocalError: local variable 'ga_params' referenced before assignment
srun: error: saliksik-gpu-05: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 276, in program_main
    continue_create_empty_yaml(newloadfile_name)
  File "main.py", line 42, in continue_create_empty_yaml
    for i in range(run_start, ga_params['run_total'] + ga_params['runs_pending']):
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: task 2: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 277, in program_main
    ga_params = conf_load(newloadfile_name)
  File "main.py", line 15, in conf_load
    return ga_params
UnboundLocalError: local variable 'ga_params' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 277, in program_main
    ga_params = conf_load(newloadfile_name)
  File "main.py", line 15, in conf_load
    return ga_params
UnboundLocalError: local variable 'ga_params' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 277, in program_main
    ga_params = conf_load(newloadfile_name)
  File "main.py", line 15, in conf_load
    return ga_params
UnboundLocalError: local variable 'ga_params' referenced before assignment
srun: error: saliksik-gpu-05: tasks 4,7-8: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: tasks 5-6: Exited with exit code 1
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 301, in main
    program_main(sys.argv)
  File "main.py", line 278, in program_main
    run_total = ga_params['run_total'] + ga_params['runs_pending']
KeyError: 'runs_pending'
srun: error: saliksik-gpu-05: tasks 9-11: Exited with exit code 1
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 237264 ON saliksik-gpu-05 CANCELLED AT 2021-07-15T15:04:09 ***
slurmstepd: error: *** STEP 237264.2 ON saliksik-gpu-05 CANCELLED AT 2021-07-15T15:04:09 ***
